### ISSUE TITLE
Notify/visualize if spending is over the monthly average

### ISSUE THREAD

**Issue by nia-potato** [electrolux-oss/infrawallet#44]
hi @gluckzhang 

Thanks for adding gcp earlier. 

I do have an additional idea. now that we can catalog all the cost for all gcp projects, is there a way we can alert/notify or have a alert within the plugin page instead of resorting to a slack integration/ or directly within the component such that if the associated gcp_project of that component has a spending average higher than last month, we can see it or be notified?   

I think the plugin itself currently tackles multicloud costs data visualization very well already, but i believe the next step is to take the data of what we process, alert users that if they are spending over their last monthly average. 

The example above is based on gcp_project_id since i know gcp environment best, but im assuming the same logic for determining if the cost was going up for a certain project-id/service-account/resource-id  logic is the same, it is just the cloud data category + resource type would be different. 

Once again this is just a an idea that i think would be helpful and bring it to your radar, it doesnt even have to be a integration to slack or directly visisble in the component overview page, it could just all be shown in the plugin page after select a specific gcp-project-id. or in backstage's logic a certain group own services that are linked to their gcp-project-id.

**Comment by gluckzhang** [comment]
Hi @nia-potato, thanks for opening such a great discussion! Yes, I very much agree with you about the plan: after cost aggregation and categorization, we need to better understand the data.

We are also having some discussions internally regarding savings, trends, alerts, etc. and we will take your feedback into consideration. Here is a question regarding your proposal and also another idea that we would like to hear your feedback.

- When you say "monthly average", do you mean the average cost of the previous X months (based on the time range you select)? then for example, we display this monthly average as a baseline in the column chart so that you can better understand the current month's costs, and get alert if it goes above the average. Does this correctly describe what you need? Or maybe you are talking about the changes compared to the last month only and when it is larger than it, you would like to have an alert.
- There are also cost optimization suggestions or insights provided by cloud providers, for example, AWS has cost [Cost Optimization Hub](https://docs.aws.amazon.com/cost-management/latest/userguide/cost-optimization-hub.html) and GCP has [FinOps hub](https://cloud.google.com/billing/docs/how-to/finops-hub). I am not sure if such information can be fetched easily using their APIs though, it could be helpful to display some suggestions on InfraWallet so that users can get these insights from different cloud providers at a single place. What do you think of this direction?

> The example above is based on gcp_project_id since i know gcp environment best, but im assuming the same logic for determining if the cost was going up for a certain project-id/service-account/resource-id logic is the same, it is just the cloud data category + resource type would be different.

Yes, this can be a generic (probably frontend) feature for any aggregations.

> Once again this is just an idea that i think would be helpful and bring it to your radar

It is helpful. Thank you again for mentioning this :)

**Comment by nia-potato** [comment]
hi @gluckzhang 

Thanks for the response!

1.  by monthly average, this was exactly what i meant 

> do you mean the average cost of the previous X months (based on the time range you select)? then for example, we display this monthly average as a baseline in the column chart so that you can better understand the current month's costs, and get alert if it goes above the average. 

2.  I took a look at what we had, (GCP) and i dont know what your experience with your providers are, but the suggestions from FinOps hub is not that useful. What i was thinking originally is a way for us to  define what are the standards of cost optimizations are for each category we recommend the users to switch to.  For instance: 

The current month's Compute Engine Cost was higher than the previous  monthly average (if we select monthly average from the above example) because each admin of each provider knows whats best to save costs based own their own infra optimizations instead of a cloud provider giving generic advice on discounts, i think a static mapping per category type which will trigger a alert only if a category was higher than average makes more sense than using FinOps hub, unless Azure's + AWSs cost optimization is really good (i may be wrong) 


if we are doing this way it would just be the plugin can read a json/yaml hosted somewhere or it can even directly live within the app config, or be mounted as a seperate configmap. 

If we take the output of the monthly average: 

-  Compute Instance cost is higher than previous month 
- within our static list that admins define in some format, we have a entry of Compute Instance High our generic solution is to either Migrate them to Spot VMs or use GKE. 

 Of course what i proposed is just one way to do this. 
 
 **Other thoughts:** 
 
 **UI:** 

-  The current overview for all providers makes sense to be all in one page, but im assuming if we were to add a alert page + average page, these would be in a separate tab. 
  
  **Additional Entity Cards** 
- Before stumbling on your plugin, i really wanted to build something similar to what you had, so i took inspiration on backstage's [Cost Insight plugin](https://demo.backstage.io/cost-insights?group=group-a&project=project-a) however their additional configurations of defining engineer costs and additional settings didnt make sense to me. But what i thought was missing at the time was if we were able to see each group owned resource Cost insights. 

If i take GCP as an example, if groupA in backstage owned these resources as type: gcp-project: 
- gcp-projectA
- gcp-projectB
- gcp-projectC 

because Infrawallet already can fetch costs based on the projectIDs, it will be able to show costs in the group page as a separate entity card. Within that card, it could just utilize the current bar chart that is separate by product/Provider category but the aggregated cost data is dependent on what the group owns for each resource, which in this case would the cost data for gcp-projectA, gcp-projectB, gcp-projectC. and then a second tab for this GroupCard can be just the alerts + suggestions. This can also be extended to the component service level. 



Sorry for the long response, I will also try to take on some PRs if there you think any of these are worth implementing.

**Comment by gluckzhang** [comment]
Hi @nia-potato, thanks for the detailed thoughts! I understand them better now.

Yes, I also agree that many suggestions from cloud providers are sort of generic. It may be better to implement something besides them. Regarding your proposals, I am thinking of breaking them into small pieces:

### For an aggregation view

The frontend can calculate the average cost of each row in a table so that it can be compared with the cost in the current period (no matter whether daily or monthly, we can always calculate an average of the selected periods, excluding the current period).

It can also be done by the backend in the future, when, for example, we would like to have a periodic task that checks and sends out alerts. For now, since the frontend gets all the needed data for any aggregations, I think we can calculate average costs in the frontend as well.

### How to display alerts

It can be a separate tab, or a panel on the same page because we already support filters, it is possible to show alerts directly when some conditions are met (such as category equals Compute)

### How to config alerts

I think we can rely on the plugin database so that such configurations can be easily changed at runtime, we also need to think about how to design these alerts (a simple way would be a set of conditions plus an alert message)

### Additional entity cards

This is also something we are thinking of, it would be very nice to integrate InfraWallet with Catalog, this task is also relatively independent of the alert one

I will also discuss the ideas with other team members next week (they are currently on vacation). At the same time, feel free to explore the code and make a PR. Or have more discussions here to inspire us both to improve the plugin :)

**Comment by nia-potato** [comment]
@gluckzhang 

Thanks for the breakdown, that makes way more sense. I will try to tinker with the codebase in the meantime.
