### ISSUE TITLE
Support tag based filtering of cost

### ISSUE THREAD

**Issue by Alok650** [electrolux-oss/infrawallet#5]
Hi 
In case of extracting data from cost explorer, can we add the functionality to filter based on a tag(s). For example, filter cost of all cloud services having tag "x". Also things like filter cost of all Lambdas having a tag "y".

**Comment by gluckzhang** [comment]
Hello :) Yeah, that would be nice to have such a feature. It may take more time because we actually need two kinds of filters:
- filters for InfraWallet options, like config name, provider, cloud service name, category, etc.
- filters when sending query requests to cloud provider

The 2nd one seems more related to your question. If we use AWS as an example, InfraWallet should support to configure the filters needed here: https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetCostAndUsage.html#awscostmanagement-GetCostAndUsage-request-Filter Tags (cost allocation tags, more specifically) are one kind of filters in this case.

It still requires more discussion and design work. Let's keep this issue open and welcome others to provide feedback as well!

**Comment by Alok650** [comment]
Hi @gluckzhang, do we have a timeline for release of this feature?

**Comment by gluckzhang** [comment]
> Hi @gluckzhang, do we have a timeline for release of this feature?

This will not happen soon. Currently, we are working on supporting the daily costs of AWS, Azure, and GCP. We plan to add some features around tagging in Q3 of this year.

**Comment by phclark** [comment]
This would be something useful for us as well, specifically the ability to group by AWS Tags.  I see that tags are a supported configuration property for AWS and Azure providers, but from what I can tell these tags are only used to aggregrated by different providers. It would by great if we could aggregate by cost allocation tags!

**Comment by gluckzhang** [comment]
Thanks for the feedback @phclark. Yes, we also need to query cost by cost allocation tags. We are working on it together with some other features. Stay tuned:
